### PR TITLE
configure-validation-handler

### LINKED ISSUE #34: Configure validation handler
Need to configure validation handler to return in response body only errors without additional information like trace id or status code

### PR DESCRIPTION
**Pull request by adrnchk**

### CODE REVIEW

**Comment by adrnchk** [comment]
Huh, I made this, but there was a... bug, I think. The fact is that fluent validation automatically handled all the wrong models instead of actionfilter so it took a long time to find the cause and eliminate it by rewriting everything
image
https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.1#automatic-http-400-responses

**Comment by adrnchk** [comment]
Now everything is working properly
image

**Comment by adrnchk** [comment]
Also I created simple models for response type error

**Comment by adrnchk** [comment]
I think it is not good practice to leave empty method even if it is not need, so I made log in it

**Review by oleh-leobit — APPROVED** [review]

**Pull request merged**
